// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.12
// source: chatgpt.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoleEnum int32

const (
	RoleEnum_System    RoleEnum = 0
	RoleEnum_Assistant RoleEnum = 1
	RoleEnum_User      RoleEnum = 2
)

// Enum value maps for RoleEnum.
var (
	RoleEnum_name = map[int32]string{
		0: "System",
		1: "Assistant",
		2: "User",
	}
	RoleEnum_value = map[string]int32{
		"System":    0,
		"Assistant": 1,
		"User":      2,
	}
)

func (x RoleEnum) Enum() *RoleEnum {
	p := new(RoleEnum)
	*p = x
	return p
}

func (x RoleEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_chatgpt_proto_enumTypes[0].Descriptor()
}

func (RoleEnum) Type() protoreflect.EnumType {
	return &file_chatgpt_proto_enumTypes[0]
}

func (x RoleEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleEnum.Descriptor instead.
func (RoleEnum) EnumDescriptor() ([]byte, []int) {
	return file_chatgpt_proto_rawDescGZIP(), []int{0}
}

type ChatGptMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Role RoleEnum `protobuf:"varint,2,opt,name=role,proto3,enum=pb.RoleEnum" json:"role,omitempty"`
}

func (x *ChatGptMessage) Reset() {
	*x = ChatGptMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatgpt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatGptMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatGptMessage) ProtoMessage() {}

func (x *ChatGptMessage) ProtoReflect() protoreflect.Message {
	mi := &file_chatgpt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatGptMessage.ProtoReflect.Descriptor instead.
func (*ChatGptMessage) Descriptor() ([]byte, []int) {
	return file_chatgpt_proto_rawDescGZIP(), []int{0}
}

func (x *ChatGptMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatGptMessage) GetRole() RoleEnum {
	if x != nil {
		return x.Role
	}
	return RoleEnum_System
}

type AnswerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages  []*ChatGptMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	MaxTokens int32             `protobuf:"varint,2,opt,name=maxTokens,proto3" json:"maxTokens,omitempty"`
}

func (x *AnswerReq) Reset() {
	*x = AnswerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatgpt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerReq) ProtoMessage() {}

func (x *AnswerReq) ProtoReflect() protoreflect.Message {
	mi := &file_chatgpt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerReq.ProtoReflect.Descriptor instead.
func (*AnswerReq) Descriptor() ([]byte, []int) {
	return file_chatgpt_proto_rawDescGZIP(), []int{1}
}

func (x *AnswerReq) GetMessages() []*ChatGptMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *AnswerReq) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type AnswerResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Choices   []*AnswerResp_Choice `protobuf:"bytes,1,rep,name=choices,proto3" json:"choices,omitempty"`
	ErrorInfo string               `protobuf:"bytes,2,opt,name=errorInfo,proto3" json:"errorInfo,omitempty"`
}

func (x *AnswerResp) Reset() {
	*x = AnswerResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatgpt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerResp) ProtoMessage() {}

func (x *AnswerResp) ProtoReflect() protoreflect.Message {
	mi := &file_chatgpt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerResp.ProtoReflect.Descriptor instead.
func (*AnswerResp) Descriptor() ([]byte, []int) {
	return file_chatgpt_proto_rawDescGZIP(), []int{2}
}

func (x *AnswerResp) GetChoices() []*AnswerResp_Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *AnswerResp) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

type AnswerResp_Choice struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message      *ChatGptMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	FinishReason string          `protobuf:"bytes,2,opt,name=finishReason,proto3" json:"finishReason,omitempty"`
	Index        int64           `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
}

func (x *AnswerResp_Choice) Reset() {
	*x = AnswerResp_Choice{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatgpt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnswerResp_Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerResp_Choice) ProtoMessage() {}

func (x *AnswerResp_Choice) ProtoReflect() protoreflect.Message {
	mi := &file_chatgpt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerResp_Choice.ProtoReflect.Descriptor instead.
func (*AnswerResp_Choice) Descriptor() ([]byte, []int) {
	return file_chatgpt_proto_rawDescGZIP(), []int{2, 0}
}

func (x *AnswerResp_Choice) GetMessage() *ChatGptMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *AnswerResp_Choice) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *AnswerResp_Choice) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_chatgpt_proto protoreflect.FileDescriptor

var file_chatgpt_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x68, 0x61, 0x74, 0x67, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x46, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x47, 0x70, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x20, 0x0a, 0x04, 0x72, 0x6f, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x6f, 0x6c,
	0x65, 0x45, 0x6e, 0x75, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x22, 0x59, 0x0a, 0x09, 0x41,
	0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x2e, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x68, 0x61, 0x74, 0x47, 0x70, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x08,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x6d, 0x61, 0x78,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22, 0xcd, 0x01, 0x0a, 0x0a, 0x41, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2f, 0x0a, 0x07, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x73, 0x77,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x07, 0x63,
	0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x70, 0x0a, 0x06, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x2c,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x47, 0x70, 0x74, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c,
	0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2a, 0x2f, 0x0a, 0x08, 0x52, 0x6f, 0x6c, 0x65, 0x45, 0x6e,
	0x75, 0x6d, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x41, 0x73, 0x73, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x55, 0x73, 0x65, 0x72, 0x10, 0x02, 0x32, 0x3b, 0x0a, 0x0e, 0x43, 0x68, 0x61, 0x74, 0x47,
	0x70, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x29, 0x0a, 0x06, 0x41, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x12, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chatgpt_proto_rawDescOnce sync.Once
	file_chatgpt_proto_rawDescData = file_chatgpt_proto_rawDesc
)

func file_chatgpt_proto_rawDescGZIP() []byte {
	file_chatgpt_proto_rawDescOnce.Do(func() {
		file_chatgpt_proto_rawDescData = protoimpl.X.CompressGZIP(file_chatgpt_proto_rawDescData)
	})
	return file_chatgpt_proto_rawDescData
}

var file_chatgpt_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatgpt_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chatgpt_proto_goTypes = []interface{}{
	(RoleEnum)(0),             // 0: pb.RoleEnum
	(*ChatGptMessage)(nil),    // 1: pb.ChatGptMessage
	(*AnswerReq)(nil),         // 2: pb.AnswerReq
	(*AnswerResp)(nil),        // 3: pb.AnswerResp
	(*AnswerResp_Choice)(nil), // 4: pb.AnswerResp.Choice
}
var file_chatgpt_proto_depIdxs = []int32{
	0, // 0: pb.ChatGptMessage.role:type_name -> pb.RoleEnum
	1, // 1: pb.AnswerReq.messages:type_name -> pb.ChatGptMessage
	4, // 2: pb.AnswerResp.choices:type_name -> pb.AnswerResp.Choice
	1, // 3: pb.AnswerResp.Choice.message:type_name -> pb.ChatGptMessage
	2, // 4: pb.ChatGptService.Answer:input_type -> pb.AnswerReq
	3, // 5: pb.ChatGptService.Answer:output_type -> pb.AnswerResp
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_chatgpt_proto_init() }
func file_chatgpt_proto_init() {
	if File_chatgpt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chatgpt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatGptMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatgpt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatgpt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatgpt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnswerResp_Choice); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chatgpt_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatgpt_proto_goTypes,
		DependencyIndexes: file_chatgpt_proto_depIdxs,
		EnumInfos:         file_chatgpt_proto_enumTypes,
		MessageInfos:      file_chatgpt_proto_msgTypes,
	}.Build()
	File_chatgpt_proto = out.File
	file_chatgpt_proto_rawDesc = nil
	file_chatgpt_proto_goTypes = nil
	file_chatgpt_proto_depIdxs = nil
}
