# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pb.chatgpt_pb2 as chatgpt__pb2


class ChatGptServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Answer = channel.unary_unary(
                '/pb.ChatGptService/Answer',
                request_serializer=chatgpt__pb2.AnswerReq.SerializeToString,
                response_deserializer=chatgpt__pb2.AnswerResp.FromString,
                )


class ChatGptServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Answer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatGptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Answer': grpc.unary_unary_rpc_method_handler(
                    servicer.Answer,
                    request_deserializer=chatgpt__pb2.AnswerReq.FromString,
                    response_serializer=chatgpt__pb2.AnswerResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.ChatGptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatGptService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Answer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.ChatGptService/Answer',
            chatgpt__pb2.AnswerReq.SerializeToString,
            chatgpt__pb2.AnswerResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
